# Generated by Django 6.0.3 on 2026-04-14 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_initial_habit_schedules(apps, schema_editor):
    Habit = apps.get_model('habits', 'Habit')
    HabitSchedule = apps.get_model('habits', 'HabitSchedule')

    for habit in Habit.objects.all():
        HabitSchedule.objects.get_or_create(
            habit=habit,
            effective_from=habit.start_date,
            defaults={'days': habit.days},
        )


def delete_initial_habit_schedules(apps, schema_editor):
    HabitSchedule = apps.get_model('habits', 'HabitSchedule')
    HabitSchedule.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_alter_habit_start_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_url', models.URLField(blank=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('non_binary', 'Non-binary'), ('prefer_not_to_say', 'Prefer not to say')], default='prefer_not_to_say', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HabitSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField()),
                ('days', models.JSONField()),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='habits.habit')),
            ],
            options={
                'ordering': ['effective_from'],
                'unique_together': {('habit', 'effective_from')},
            },
        ),
        migrations.RunPython(create_initial_habit_schedules, delete_initial_habit_schedules),
    ]
