# Generated by Django 6.0.3 on 2026-04-14 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_userprofile_habitschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
