# Generated by Django 6.0.3 on 2026-04-14 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0005_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='archived_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
