# Generated by Django 6.0.3 on 2026-04-17 00:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0006_habit_archived_at_habit_is_archived'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='habit',
            index=models.Index(fields=['user', 'is_archived'], name='habit_user_arch_idx'),
        ),
        migrations.AddIndex(
            model_name='habit',
            index=models.Index(fields=['user', 'start_date'], name='habit_user_start_idx'),
        ),
        migrations.AddIndex(
            model_name='habitlog',
            index=models.Index(fields=['date'], name='habitlog_date_idx'),
        ),
        migrations.AddIndex(
            model_name='habitlog',
            index=models.Index(fields=['date', 'status'], name='habitlog_date_status_idx'),
        ),
    ]
